<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class SmBookIssue extends Model
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($row){
            $year = SmGeneralSettings::where('school_id',Auth::user()->school_id)->first();
            $row->year_id = $year->session_id;
            $row->save();
        });
    }
    public function books(){
    	return $this->belongsTo('App\SmBook', 'book_id', 'id');
    }
    public function getRemainingDaysAttribute()
    {

        if ($this->due_date) {
            $remaining_days = Carbon::now()->diffInDays(Carbon::parse($this->due_date));
        } else {
            $remaining_days = 0;
        }
        return $remaining_days;
    }
}
